name: .NET CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wagoid/commitlint-github-action@v5

  build:
    runs-on: windows-latest
    needs: commitlint
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Upload source code for test
      uses: actions/upload-artifact@v4
      with:
        name: source-code
        path: . # 上傳整個 repo，包括 .sln、.csproj、src、tests 等

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - name: Download source code
      uses: actions/download-artifact@v4
      with:
        name: source-code
        path: ./repo
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Run tests
      run: |
        cd ./repo
        dotnet test --configuration Release
